[theme]
primaryColor = '#000000'  # Black
backgroundColor = '#F0F0F0'  # Light Gray
secondaryBackgroundColor = '#E0E0E0'  # Slightly Darker Gray
textColor = '#000000'  # Black
font = "sans serif"  # Using a generic sans-serif font
